---
defaultBaseImage: cgr.dev/chainguard/static

builds:
  - id: gh-jira-issue-sync
    dir: .
    main: ./main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-static"
      - "{{ .Env.GHJIRA_LDFLAGS }}"
